# Generated by Django 3.2.12 on 2023-06-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='futureOwner',
            field=models.IntegerField(blank=True, null=True, verbose_name='Future Product Owner'),
        ),
        migrations.AddField(
            model_name='products',
            name='requested',
            field=models.BooleanField(default=True),
        ),
    ]
