# Generated by Django 4.0.2 on 2022-02-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('database', 'database'), ('acckey', 'acckey'), ('notebook', 'notebook'), ('etc', 'etc')], default='etc', max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(default='no_image.jpg', upload_to='product_image'),
        ),
        migrations.AddField(
            model_name='products',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=10, verbose_name='price'),
        ),
    ]
