# Generated by Django 3.2.12 on 2023-06-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230604_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='fileEntity',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
