# Generated by Django 4.0.2 on 2022-02-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_products_options_products_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('database', 'database'), ('etc', 'etc'), ('notebook', 'notebook'), ('acckey', 'acckey')], default='etc', max_length=10),
        ),
    ]
