# Generated by Django 3.2.12 on 2023-06-04 16:49

import Services.formatChecker
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230604_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='fileEntity',
            field=Services.formatChecker.ContentTypeRestrictedFileField(upload_to='files/'),
        ),
    ]
