# Generated by Django 4.0.2 on 2022-03-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_alter_products_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='owner',
            field=models.CharField(default='admin', max_length=50, verbose_name='owner'),
        ),
    ]
