# Generated by Django 4.0.2 on 2022-03-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_products_description_alter_products_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='owner',
            field=models.IntegerField(verbose_name='Product Owner'),
        ),
    ]
