# Generated by Django 3.2.12 on 2022-04-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_products_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=400, verbose_name='comments')),
                ('target', models.IntegerField(verbose_name='Review Target')),
                ('product_raiting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.raiting')),
            ],
        ),
    ]
