# Generated by Django 3.2.12 on 2022-04-20 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_raiting_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='autor_raiting',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='autor_raiting', to='main.raiting'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product_raiting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_raiting', to='main.raiting'),
        ),
    ]
