# Generated by Django 3.2.12 on 2022-05-18 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220420_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='products',
            name='fileEntity',
            field=models.FileField(default=django.utils.timezone.now, upload_to='files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='autor_raiting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_raiting', to='main.raiting'),
        ),
    ]
