# Generated by Django 4.0.2 on 2022-03-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FB_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='admin', max_length=50, verbose_name='username')),
                ('firstname', models.CharField(default='ad', max_length=50, verbose_name='firstname')),
                ('lastname', models.CharField(default='min', max_length=50, verbose_name='lastname')),
                ('wallet', models.IntegerField(default='1000', verbose_name='wallet')),
            ],
        ),
    ]
