# Generated by Django 3.2.12 on 2022-05-18 15:22

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fb_user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='fb_user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='fb_user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='fb_user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fb_user',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='fb_user',
            name='username',
        ),
        migrations.RemoveField(
            model_name='fb_user',
            name='wallet',
        ),
        migrations.AddField(
            model_name='fb_user',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user'),
            preserve_default=False,
        ),
    ]
